### ISSUE TITLE
The assembly 'Cake.Xamarin, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'  is referencing an older version of Cake.Core (0.22.0).

### ISSUE THREAD

**Issue by davidsonblake** [cake-contrib/Cake.Xamarin#22]
It looks like Cake.Xamarin might need to be upgraded to use Cake.Core 0.26 or greater.

The assembly 'Cake.Xamarin, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null' 
is referencing an older version of Cake.Core (0.22.0). 
This assembly need to reference at least Cake.Core version 0.26.0. 
Another option is to downgrade Cake to an earlier version. 
It's not recommended, but you can explicitly opt-out of assembly verification 
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true", 
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true", 
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)

**Comment by gep13** [comment]
@davidsonblake this has been fixed in the latest release.  Let us know if you still have issues.
